import { widgets } from './WidgetsConfig';

interface Component {
  name: string;
  id: string;
  autogenerated: boolean;
}

// enum EventTypes {
//   onClick,
//   onHover,
//   onRowHovered,
//   onRowClicked,
//   onBulkUpdate,
//   onPageChanged,
//   onSearch,
//   onCancelChanges,
//   onSort,
//   onCellValueChanged,
//   onFilterChanged,
//   onNewRowsAdded,
//   onSubmit,
//   onInvalid
// }

interface IEventType {
  displayName: string;
}

interface Actions {
  handle: string;
  displayName: string;
  params?: unknown[];
}

type EventName = {
  displayName: string;
}
export interface Widget {
  name?: string;
  displayName?: string;
  description?: string;
  component?: string;
  defaultSize?: {
    width?: number;
    height?: number;
  };
  properties?: object;
  defaultChildren?: object;
  general?: {
    tooltip?: {
      type?: string;
      displayName?: string;
      validation: { schema: { type?: string } };
    };
  };
  others?: object;
  events?:
    | {
        key: EventName;
      }
    | Array<{ key: { displayName: string } }>
    | object
    | [];
  // {
  //       onClick?: {
  //         displayName: string;
  //       };
  //       onHover?: {
  //         displayName: string;
  //       };
  //       onRowHovered?: {
  //         displayName: string;
  //       };
  //       onRowClicked?: {
  //         displayName: string;
  //       };
  //       onBulkUpdate?: {
  //         displayName: string;
  //       };
  //       onPageChanged?: {
  //         displayName: string;
  //       };
  //       onSearch?: {
  //         displayName: string;
  //       };
  //       onCancelChanges?: {
  //         displayName: string;
  //       };
  //       onSort?: {
  //         displayName: string;
  //       };
  //       onCellValueChanged?: {
  //         displayName: string;
  //       };
  //       onFilterChanged?: {
  //         displayName: string;
  //       };
  //       onNewRowsAdded?: {
  //         displayName: string;
  //       };
  //       onSubmit?: {
  //         displayName: string;
  //       };
  //       onInvalid?: {
  //         displayName: string;
  //       };
  //     }
  styles?: object;
  validate?: boolean;
  generalStyles?: {
    boxShadow?: { type?: string; displayName?: string };
  };
  definition?: {
    others?: object;
    events?: object;
    styles?: object;
    generalStyles?: {
      boxShadow: { value?: string };
    };
    properties?: {
      title?: {
        value: string;
      };
      visible?: {
        value: string;
      };
      data?: {
        value: string;
      };
      useDynamicColumn?: {
        value: string;
      };
      columnData?: {
        value: string;
      };
      rowsPerPage?: {
        value: string;
      };
      serverSidePagination?: {
        value: string;
      };
      enableNextButton?: {
        value: string;
      };
      enablePrevButton?: {
        value: string;
      };
      totalRecords?: {
        value: string;
      };
      clientSidePagination?: {
        value: string;
      };
      serverSideSort?: {
        value: string;
      };
      serverSideFilter?: {
        value: string;
      };
      displaySearchBox?: {
        value: string;
      };
      showDownloadButton?: {
        value: string;
      };
      showFilterButton?: {
        value: string;
      };
      autogenerateColumns?: {
        value: boolean;
        generateNestedColumns: boolean;
      };
      columns?: {
        value: Component[];
      };
      showBulkUpdateActions?: {
        value: string;
      };
      showBulkSelector?: {
        value: string;
      };
      highlightSelectedRow?: {
        value: string;
      };
      columnSizes?: {
        value: string;
      };
      actions?: {
        value: [];
      };
      enabledSort?: {
        value: string;
      };
      hideColumnSelectorButton?: {
        value: string;
      };
      defaultSelectedRow?: {
        value: string;
      };
      showAddNewRowButton?: {
        value: string;
      };
      allowSelection?: {
        value: string;
      };
      text?: {
        value: string;
      };
      loadingState?: {
        value: string;
      };
      advanced?: {
        value: string;
      };
      JSONSchema?: {
        value: string;
      };
    };
  };
  exposedVariables?: object;
  actions?: Actions[];
}

const universalProps: Widget = {
  properties: {},
  general: {
    tooltip: {
      type: 'code',
      displayName: 'Tooltip',
      validation: { schema: { type: 'string' } }
    }
  },
  others: {},
  events: {} | [],
  styles: {},
  validate: true,
  generalStyles: {
    boxShadow: { type: 'boxShadow', displayName: 'Box Shadow' }
  },
  definition: {
    others: {},
    events: [],
    styles: {},
    generalStyles: {
      boxShadow: { value: '0px 0px 0px 0px #00000040' }
    }
  },
  exposedVariables: {}
};

const combineProperties = (
  widget: Widget,
  universal: Widget,
  isArray: boolean = false
): Widget => {
  return {
    ...universal,
    ...widget,
    properties: { ...universal.properties, ...widget.properties },
    general: { ...universal.general, ...widget.general },
    others: { ...universal.others, ...widget.others },
    // events: isArray
    //   ? [...universal.events, ...widget.events]
    //   : { ...universal.events, ...widget.events },
    styles: { ...universal.styles, ...widget.styles },
    generalStyles: { ...universal.generalStyles, ...widget.generalStyles },
    exposedVariables: {
      ...universal.exposedVariables,
      ...widget.exposedVariables
    }
  };
};

export const componentTypes: Widget[] = widgets.map(widget => {
  return {
    ...combineProperties(widget, universalProps)
    // definition: combineProperties(widget.definition, universalProps.definition, true)
  };
});
